In [2]:
import numpy as np

## EXERCISE 4

#### 1. create a null vector / 1D array of size 10 and update fifth value to 11.

In [6]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
a[4] = 11
a

array([ 0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.,  0.])

#### 2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [3]:
b = np.array([[1,2,3],
             [7,8,9]
             ])
b

array([[1, 2, 3],
       [7, 8, 9]])

In [4]:
b.reshape(3,2)

array([[1, 2],
       [3, 7],
       [8, 9]])

#### 3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside

In [31]:
c = np.ones((5,5))
print('Original array:\n', c)

Original array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
c[1:-1,1:-1] = 0
print('1 on the border and 0 inside:\n', c)

1 on the border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 4. Take a look at the following matrix. Access the [2, 1,1]

In [7]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])
z

array([[[ 0,  1,  3],
        [ 5,  7,  9],
        [ 6,  8, 10]],

       [[ 0,  2,  4],
        [ 6,  8, 10],
        [ 0,  1,  3]],

       [[ 1,  1,  2],
        [ 5,  2,  9],
        [ 1,  3,  3]]])

In [56]:
z[2,1,1:]

array([2, 9])

## ASSIGNMENT

#### 1. Create a 4x4 matrix with values ranging from 0 to 3

In [14]:
x = np.zeros((4,4))
x += np.arange(4)

x

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

#### 2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.

In [19]:
np.hsplit(x, 2)

[array([[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]]),
 array([[2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.]])]